# Generated by Django 5.2.8 on 2025-11-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=5)),
                ('department', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=250)),
            ],
        ),
    ]
