# Generated by Django 5.2.8 on 2025-11-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='roll',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
