# Generated by Django 5.2.8 on 2025-11-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_studentmodel_age_studentmodel_roll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
