# Generated by Django 5.2.8 on 2025-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_studentmodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
